# Generated by Django 5.2.5 on 2025-09-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_category_alter_receita_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='category',
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('sobremesa', 'Sobremesa'), ('drink', 'Drink')], default='comida', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='instructions',
            field=models.TextField(verbose_name='Modo de preparo'),
        ),
    ]
